#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/home/bshayne/.dotfiles/bash_profile" "/home/bshayne/.bash_profile"
handle_file_ln "/home/bshayne/.dotfiles/bashrc" "/home/bshayne/.bashrc"
handle_file_ln "/home/bshayne/.dotfiles/dircolors" "/home/bshayne/.dircolors"
handle_file_ln "/home/bshayne/.dotfiles/dircolors.256dark" "/home/bshayne/.dircolors.256dark"
handle_file_ln "/home/bshayne/.dotfiles/dircolors.ansi-universal" "/home/bshayne/.dircolors.ansi-universal"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/backups/!home!bshayne!.tmux.conf.~1~" "/home/bshayne/.emacs.d/backups/!home!bshayne!.tmux.conf.~1~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/backups/!home!bshayne!.tmux.conf.~2~" "/home/bshayne/.emacs.d/backups/!home!bshayne!.tmux.conf.~2~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/backups/!home!bshayne!.tmux.conf.~3~" "/home/bshayne/.emacs.d/backups/!home!bshayne!.tmux.conf.~3~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/backups/!home!bshayne!.tmux.conf.local.~1~" "/home/bshayne/.emacs.d/backups/!home!bshayne!.tmux.conf.local.~1~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/backups/!home!bshayne!.tmux.conf.local.~2~" "/home/bshayne/.emacs.d/backups/!home!bshayne!.tmux.conf.local.~2~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/elpa/archives/gnu/archive-contents" "/home/bshayne/.emacs.d/elpa/archives/gnu/archive-contents"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/elpa/archives/gnu/archive-contents.signed" "/home/bshayne/.emacs.d/elpa/archives/gnu/archive-contents.signed"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/elpa/gnupg/pubring.kbx" "/home/bshayne/.emacs.d/elpa/gnupg/pubring.kbx"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/elpa/gnupg/pubring.kbx~" "/home/bshayne/.emacs.d/elpa/gnupg/pubring.kbx~"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/elpa/gnupg/trustdb.gpg" "/home/bshayne/.emacs.d/elpa/gnupg/trustdb.gpg"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/init.el" "/home/bshayne/.emacs.d/init.el"
handle_file_ln "/home/bshayne/.dotfiles/emacs.d/places" "/home/bshayne/.emacs.d/places"
handle_file_ln "/home/bshayne/.dotfiles/gitconfig" "/home/bshayne/.gitconfig"
handle_file_ln "/home/bshayne/.dotfiles/install.sh" "/home/bshayne/.install.sh"
handle_file_ln "/home/bshayne/.dotfiles/README.md" "/home/bshayne/.README.md"
handle_file_ln "/home/bshayne/.dotfiles/screenrc" "/home/bshayne/.screenrc"
handle_file_ln "/home/bshayne/.dotfiles/ssh/config" "/home/bshayne/.ssh/config"
handle_file_ln "/home/bshayne/.dotfiles/tmux.conf" "/home/bshayne/.tmux.conf"
handle_file_ln "/home/bshayne/.dotfiles/vim/autoload/togglebg.vim" "/home/bshayne/.vim/autoload/togglebg.vim"
handle_file_ln "/home/bshayne/.dotfiles/vim/bitmaps/togglebg.png" "/home/bshayne/.vim/bitmaps/togglebg.png"
handle_file_ln "/home/bshayne/.dotfiles/vim/colors/solarized.vim" "/home/bshayne/.vim/colors/solarized.vim"
handle_file_ln "/home/bshayne/.dotfiles/vim/doc/solarized.txt" "/home/bshayne/.vim/doc/solarized.txt"
handle_file_ln "/home/bshayne/.dotfiles/vim/doc/tags" "/home/bshayne/.vim/doc/tags"
handle_file_ln "/home/bshayne/.dotfiles/vimrc" "/home/bshayne/.vimrc"
handle_file_ln "/home/bshayne/.dotfiles/zshrc" "/home/bshayne/.zshrc"
